version: '3'
services:
  userver-mail:
    container_name: userver-mail
    restart: unless-stopped
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - mail-data:/var/mail
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - ./mail/config/:/tmp/docker-mailserver/
    env_file:
      - mail/.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  userver-mailbackup:
    image: tiberiuc/backup-service
    container_name: userver-mailbackup
    restart: unless-stopped
    depends_on:
      - userver-mail
    env_file:
      - ./backup/.env
    volumes:
      - mail-data:/backup/mail-data
      - mail-state:/backup/mail-state
      - mail-logs:/backup/mail-logs

  userver-webmail:
    container_name: userver-webmail
    restart: unless-stopped
    build:
      context: ./webmail
      dockerfile: Dockerfile
    depends_on:
      - userver-mail
    env_file:
      - webmail/.env
    expose:
      - 80
    volumes:
      - ../userver-web/certs:/certs:ro
      - ./webmail/sites-available:/etc/apache2/sites-available

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  mail-data:
  mail-state:
  mail-logs:
