version: '3'
services:
  userver-mail:
    container_name: userver-mail
    restart: unless-stopped
    image: tvial/docker-mailserver:release-v7.2.0
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./data:/var/mail
      - ./state:/var/mail-state
      - ./logs:/var/log/mail
      - ./mail/config/:/tmp/docker-mailserver/
      - ../userver-web/certs:/etc/letsencrypt/live
    env_file:
      - ./mail/.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  userver-mailbackup:
    build:
      context: backup
      dockerfile: Dockerfile
    container_name: userver-mailbackup
    restart: unless-stopped
    depends_on:
      - userver-mail
    env_file:
      - ./backup/.env
    volumes:
      - ./data:/data/mail-data:ro
      - ./state:/data/mail-state:ro
      - ./logs:/data/mail-logs:ro

  userver-webmail:
    container_name: userver-webmail
    restart: unless-stopped
    image: roundcube/roundcubemail:1.5.x-apache
    depends_on:
      - userver-mail
    env_file:
      - ./webmail/.env
    expose:
      - 80
    volumes:
      - ../userver-web/certs:/certs:ro
      - ./webmail/sites-available:/etc/apache2/sites-available
      - ./webmail/config:/var/roundcube/config

  userver-postfixadmin:
    container_name: userver-postfixadmin
    restart: unless-stopped
    build:
      context: postfixadmin
      dockerfile: Dockerfile
    image: postfixadmin:3-apache
    expose:
      - 80
    env_file:
      - ./postfixadmin/.env

networks:
  default:
    name: nginx-proxy
    external: true
